In [267]:
import os, glob
import pandas as pd

# Transform data only run once

In [268]:
# PATH = "/Users/apple/Desktop/Development/freelance/upwork/brad-miles/Landmarks-Detection/Dataset/Landmarks"
# NEW_PATH = "/Users/apple/Desktop/Development/freelance/upwork/brad-miles/Landmarks-Detection/Dataset/csvs-patella/"
# files = glob.glob(PATH + '/Patella/*.csv', recursive=True)
# text = "landmark,x, y, z\n"
# for file in files:
#     with open(file) as f:
#         data = f.read()
#     new_data = text + data
#     splited = file.rsplit('/', 2)
#     path_to_store = NEW_PATH + "{} {}".format(splited[1], splited[2])
#     with open(path_to_store, "w+") as fn:
#         fn.write(new_data)

# Remove femCMPImportREF

## Only run once

In [269]:
# PATH = "/Users/apple/Desktop/Development/freelance/upwork/brad-miles/Landmarks-Detection/Dataset/csvs-patella/"
# files = glob.glob(PATH + '/*.csv', recursive=True)
# for file in files:
#     with open(file) as f:
#         data = f.readlines()
#     if "patCMPImportREF" in data[-1]:
#         new_data = data[:len(data)-1]
#     else:
#         new_data = data
#     new_data = "".join(new_data)
#     splited = file.rsplit('/', 2)
#     path_to_store = file
#     with open(path_to_store, "w+") as fn:
#         fn.write(new_data)

# Data Preprocessing

In [270]:
PATH = "/Users/apple/Desktop/Development/freelance/upwork/brad-miles/Landmarks-Detection/Dataset/csvs-patella/"
files = glob.glob(PATH + '/*.csv', recursive=True)

In [271]:
#defining known and unknown landmarks
landmarks = [
    "anteriorApex",
    "quadTendonInsertion",
    "patTendonOrigin",
    "MedialEdge",
    "LateralEdge",
    "posteriorApex"
]

known_landmarks = [
    "anteriorApex",
    "quadTendonInsertion",
    "patTendonOrigin",
    "MedialEdge",
    "LateralEdge"
]

unknown_landmarks = [
    "posteriorApex"
]

In [272]:
# Loading train dataset
df = pd.DataFrame()
for file in files:
    df1 = pd.read_csv(file).transpose()
    temp = []
    for item in df1.iloc[0]:
        temp.append(item)
    df1.columns = temp
    df = df.append(df1[1:4])

In [273]:
df.head()

,anteriorApex,quadTendonInsertion,patTendonOrigin,MedialEdge,LateralEdge,posteriorApex
x,-122.14,-122.06,-122.6,-101.96,-141.71,-118.06
y,-190.3,-182.59,-181.9,-183.23,-177.9,-172.5
z,-576.95,-558.89,-595.71,-573.82,-573.6,-574.81
x,83.61,85.07,87.85,64.9,107.85,85
y,-41.93,-37.74,-31.52,-32.39,-35.93,-22.2

In [274]:
# spliting trin dataset
df_x = df[known_landmarks]
df_y = df[unknown_landmarks]

In [275]:
df_x.head()

   anteriorApex quadTendonInsertion patTendonOrigin MedialEdge LateralEdge
x       -122.14             -122.06          -122.6    -101.96     -141.71
 y       -190.3             -182.59          -181.9    -183.23      -177.9
 z      -576.95             -558.89         -595.71    -573.82      -573.6
x         83.61               85.07           87.85       64.9      107.85
 y       -41.93              -37.74          -31.52     -32.39      -35.93

In [276]:
df_y.head()

   posteriorApex
x        -118.06
 y        -172.5
 z       -574.81
x             85
 y         -22.2

In [277]:
# Transforming dataframe so that each patient is represented as 1 example to model

new_known_landmarks = []
for item in df_x.columns:
    new_known_landmarks.append(item + "_x")
    new_known_landmarks.append(item+"_y")
    new_known_landmarks.append(item+"_z")
    
new_df = []
for i in range(0, len(df_x), 3):
    row = [] 
    temp = df_x.iloc(0)
    for item in known_landmarks:
        row.append(temp[i][item])
        row.append(temp[i+1][item])
        row.append(temp[i+2][item])
    new_df.append(row)
new_df_x = pd.DataFrame(new_df)
new_df_x.columns = new_known_landmarks

In [278]:
new_df_x.head()

,anteriorApex_x,anteriorApex_y,anteriorApex_z,quadTendonInsertion_x,quadTendonInsertion_y,quadTendonInsertion_z,patTendonOrigin_x,patTendonOrigin_y,patTendonOrigin_z,MedialEdge_x,MedialEdge_y,MedialEdge_z,LateralEdge_x,LateralEdge_y,LateralEdge_z
0,-122.14,-190.30,-576.95,-122.06,-182.59,-558.89,-122.60,-181.90,-595.71,-101.96,-183.23,-573.82,-141.71,-177.90,-573.60
1,83.61,-41.93,912.33,85.07,-37.74,935.37,87.85,-31.52,897.14,64.90,-32.39,922.09,107.85,-35.93,919.89
2,111.08,98.09,-531.41,114.82,106.96,-509.35,115.72,108.63,-553.57,91.45,107.69,-526.56,142.44,111.91,-521.90
3,126.59,-180.76,995.14,128.74,-172.20,1017.95,124.96,-169.53,979.37,106.78,-180.55,1000.25,142.60,-153.18,1001.90
4,-115.76,-61.70,-537.60,-115.50,-54.28,-520.75,-114.92,-49.68,-564.67,-94.97,-59.01,-540.02,-139.97,-50.26,-537.76

In [279]:
# Transforming dataframe so that each patient is represented as 1 example to model

new_unknown_landmarks = []
for item in unknown_landmarks:
    new_unknown_landmarks.append(item + "_x")
    new_unknown_landmarks.append(item+"_y")
    new_unknown_landmarks.append(item+"_z")
    
new_df = []
for i in range(0, len(df_y), 3):
    row = [] 
    temp = df_y.iloc(0)
    for item in unknown_landmarks:
        row.append(temp[i][item])
        row.append(temp[i+1][item])
        row.append(temp[i+2][item])
    new_df.append(row)
    
new_df_y = pd.DataFrame(new_df)
new_df_y.columns = new_unknown_landmarks

In [280]:
new_df_y["posteriorApex_x"].head()

0   -118.06
1     85.00
2    112.86
3    114.68
4   -111.92
Name: posteriorApex_x, dtype: float64

In [281]:
new_df_x.head()

,anteriorApex_x,anteriorApex_y,anteriorApex_z,quadTendonInsertion_x,quadTendonInsertion_y,quadTendonInsertion_z,patTendonOrigin_x,patTendonOrigin_y,patTendonOrigin_z,MedialEdge_x,MedialEdge_y,MedialEdge_z,LateralEdge_x,LateralEdge_y,LateralEdge_z
0,-122.14,-190.30,-576.95,-122.06,-182.59,-558.89,-122.60,-181.90,-595.71,-101.96,-183.23,-573.82,-141.71,-177.90,-573.60
1,83.61,-41.93,912.33,85.07,-37.74,935.37,87.85,-31.52,897.14,64.90,-32.39,922.09,107.85,-35.93,919.89
2,111.08,98.09,-531.41,114.82,106.96,-509.35,115.72,108.63,-553.57,91.45,107.69,-526.56,142.44,111.91,-521.90
3,126.59,-180.76,995.14,128.74,-172.20,1017.95,124.96,-169.53,979.37,106.78,-180.55,1000.25,142.60,-153.18,1001.90
4,-115.76,-61.70,-537.60,-115.50,-54.28,-520.75,-114.92,-49.68,-564.67,-94.97,-59.01,-540.02,-139.97,-50.26,-537.76

# Model Training

In [282]:
from sklearn import linear_model

## posteriorApex training

In [283]:
lm_x_po = linear_model.LinearRegression()
model_x = lm_x_po.fit(new_df_x,new_df_y["posteriorApex_x"])
lm_y_po = linear_model.LinearRegression()
model_y = lm_y_po.fit(new_df_x,new_df_y["posteriorApex_y"])
lm_z_po = linear_model.LinearRegression()
model_z = lm_z_po.fit(new_df_x,new_df_y["posteriorApex_z"])

# Prediction testing

In [284]:
PATH = "/Users/apple/Desktop/Development/freelance/upwork/brad-miles/Landmarks-Detection/Dataset/csvs-test-petella/"
files = glob.glob(PATH + '/*.csv', recursive=True)

In [285]:
# Loading test dataset
df = pd.DataFrame()
for file in files:
    df1 = pd.read_csv(file).transpose()
    temp = []
    for item in df1.iloc[0]:
        temp.append(item)
    df1.columns = temp
    df = df.append(df1[1:4])

In [286]:
# spliting test dataset
df_x = df[known_landmarks]
df_y = df[unknown_landmarks]

In [287]:
# transforming test dataset for prediction
new_known_landmarks = []
for item in df_x.columns:
    new_known_landmarks.append(item + "_x")
    new_known_landmarks.append(item+"_y")
    new_known_landmarks.append(item+"_z")
    
new_df = []
for i in range(0, len(df_x), 3):
    row = [] 
    temp = df_x.iloc(0)
    for item in known_landmarks:
        row.append(temp[i][item])
        row.append(temp[i+1][item])
        row.append(temp[i+2][item])
    new_df.append(row)
new_df_x = pd.DataFrame(new_df)
new_df_x.columns = new_known_landmarks

In [288]:
# transforming test dataset for prediction

new_unknown_landmarks = []
for item in unknown_landmarks:
    new_unknown_landmarks.append(item + "_x")
    new_unknown_landmarks.append(item+"_y")
    new_unknown_landmarks.append(item+"_z")
    
new_df = []
for i in range(0, len(df_y), 3):
    row = [] 
    temp = df_y.iloc(0)
    for item in unknown_landmarks:
        row.append(temp[i][item])
        row.append(temp[i+1][item])
        row.append(temp[i+2][item])
    new_df.append(row)
    
new_df_y = pd.DataFrame(new_df)
new_df_y.columns = new_unknown_landmarks

## posteriorApex_test

In [289]:
#pedict posteriorApex 
predictions_x = lm_x_po.predict(new_df_x)
predictions_y = lm_y_po.predict(new_df_x)
predictions_z = lm_z_po.predict(new_df_x)
posteriorApex_predictions = []
for i, x in enumerate(predictions_z):
    posteriorApex_predictions.append([predictions_x[i], predictions_y[i], x])

In [290]:
posteriorApex_df = pd.DataFrame(posteriorApex_predictions)
posteriorApex_df.columns= ["posteriorApex_x", "posteriorApex_y", "posteriorApex_z"]
print("\nPredicted Values!!!")
posteriorApex_df

Predicted Values!!!

   posteriorApex_x  posteriorApex_y  posteriorApex_z
0        69.623368       -56.831808       995.488042
1       131.967847       -88.637495      -529.221057
2        73.982106      -152.390647      -557.238945
3       -68.999539        -7.706571      1013.413525
4       114.005765       -15.601430      1138.819350

In [291]:
print("\nActual Values!!!")
new_df_y[["posteriorApex_x", "posteriorApex_y", "posteriorApex_z"]]

Actual Values!!!

   posteriorApex_x  posteriorApex_y  posteriorApex_z
0            68.88           -58.50           992.98
1           128.49           -89.75          -528.24
2            72.52          -150.30          -557.49
3           -67.48            -5.87          1015.05
4           111.96           -14.88          1141.65