In [1]:
import os, glob
import pandas as pd

# Transform data only run once

In [2]:
# PATH = "/Users/apple/Desktop/Development/freelance/upwork/brad-miles/Landmarks-Detection/Dataset/Landmarks"
# NEW_PATH = "/Users/apple/Desktop/Development/freelance/upwork/brad-miles/Landmarks-Detection/Dataset/csvs/"
# files = glob.glob(PATH + '/Femur/*.csv', recursive=True)
# text = "landmark,x, y, z\n"
# for file in files:
#     with open(file) as f:
#         data = f.read()
#     new_data = text + data
#     splited = file.rsplit('/', 2)
#     path_to_store = NEW_PATH + "{} {}".format(splited[1], splited[2])
#     with open(path_to_store, "w+") as fn:
#         fn.write(new_data)

# Remove femCMPImportREF

## Only run once

In [3]:
# PATH = "/Users/apple/Desktop/Development/freelance/upwork/brad-miles/Landmarks-Detection/Dataset/csvs/"
# files = glob.glob(PATH + '/*.csv', recursive=True)
# for file in files:
#     with open(file) as f:
#         data = f.readlines()
#     if "femCMPImportREF" in data[-1]:
#         new_data = data[:len(data)-1]
#     else:
#         new_data = data
#     new_data = "".join(new_data)
#     splited = file.rsplit('/', 2)
#     path_to_store = file
#     with open(path_to_store, "w+") as fn:
#         fn.write(new_data)

# Data Preprocessing

In [4]:
PATH = "/Users/apple/Desktop/Development/freelance/upwork/brad-miles/Landmarks-Detection/Dataset/csvs/"
files = glob.glob(PATH + '/*.csv', recursive=True)

In [5]:
#defining known and unknown landmarks
landmarks = [
    'PCLOrigin',
    'femoralCenter',
    'greaterTrochanter',
    'hipCenter',
    'lateralCondyle',
    'lateralEpicondyle',
    'lateralPosteriorCondyle',
    'medialCondyle',
    'medialEpicondyle',
    'medialPosteriorCondyle',
    'medialSulcus',
    'midfemurCenter',
    'whitesideReference'
]
#    'femoralCenter',
known_landmarks = [
    'greaterTrochanter',
    'hipCenter',
    'lateralEpicondyle',
    'lateralPosteriorCondyle',
    'medialEpicondyle',
    'medialPosteriorCondyle',
    'midfemurCenter'
]

unknown_landmarks = [
    'PCLOrigin',
    'lateralCondyle',
    'medialCondyle',
    'medialSulcus',
    'femoralCenter',
    'whitesideReference'
]

In [6]:
# Loading train dataset
df = pd.DataFrame()
for file in files:
    df1 = pd.read_csv(file).transpose()
    temp = []
    for item in df1.iloc[0]:
        temp.append(item)
    df1.columns = temp
    df = df.append(df1[1:4])

In [7]:
df.head()

,PCLOrigin,femoralCenter,greaterTrochanter,hipCenter,lateralCondyle,lateralEpicondyle,lateralPosteriorCondyle,medialCondyle,medialEpicondyle,medialPosteriorCondyle,medialSulcus,midfemurCenter,whitesideReference
x,-64.01,-73.9,-138.02,-85.67,-101.32,-116.63,-100.89,-48.14,-31.03,-49.27,-33.2,-98.24,-68.86
y,26.89,1.9,22.78,6.7,13.8,12.84,41.54,14.06,15.25,47.38,23.46,-1.3,-17.45
z,498.21,475.64,984.23,983.37,468.11,496.29,490.52,465.61,496.03,489.43,493.23,736.86,491.42
x,120.63,134.17,147.21,100.45,154.5,170.56,152.07,107.65,89.09,107.31,90.65,140.35,135.83
y,-0.79,-22.04,17,-4.38,-13.86,-4.26,17.91,-17.06,-20,15.19,-12.16,-17.56,-45.36

In [8]:
# spliting trin dataset
df_x = df[known_landmarks]
df_y = df[unknown_landmarks]

In [9]:
df_x.head()

,greaterTrochanter,hipCenter,lateralEpicondyle,lateralPosteriorCondyle,medialEpicondyle,medialPosteriorCondyle,midfemurCenter
x,-138.02,-85.67,-116.63,-100.89,-31.03,-49.27,-98.24
y,22.78,6.7,12.84,41.54,15.25,47.38,-1.3
z,984.23,983.37,496.29,490.52,496.03,489.43,736.86
x,147.21,100.45,170.56,152.07,89.09,107.31,140.35
y,17,-4.38,-4.26,17.91,-20,15.19,-17.56

In [10]:
df_y.head()

,PCLOrigin,lateralCondyle,medialCondyle,medialSulcus,femoralCenter,whitesideReference
x,-64.01,-101.32,-48.14,-33.2,-73.9,-68.86
y,26.89,13.8,14.06,23.46,1.9,-17.45
z,498.21,468.11,465.61,493.23,475.64,491.42
x,120.63,154.5,107.65,90.65,134.17,135.83
y,-0.79,-13.86,-17.06,-12.16,-22.04,-45.36

In [11]:
# Transforming dataframe so that each patient is represented as 1 example to model

new_known_landmarks = []
for item in df_x.columns:
    new_known_landmarks.append(item + "_x")
    new_known_landmarks.append(item+"_y")
    new_known_landmarks.append(item+"_z")
    
new_df = []
for i in range(0, len(df_x), 3):
    row = [] 
    temp = df_x.iloc(0)
    for item in known_landmarks:
        row.append(temp[i][item])
        row.append(temp[i+1][item])
        row.append(temp[i+2][item])
    new_df.append(row)
new_df_x = pd.DataFrame(new_df)
new_df_x.columns = new_known_landmarks

In [12]:
new_df_x.head()

,greaterTrochanter_x,greaterTrochanter_y,greaterTrochanter_z,hipCenter_x,hipCenter_y,hipCenter_z,lateralEpicondyle_x,lateralEpicondyle_y,lateralEpicondyle_z,lateralPosteriorCondyle_x,...,lateralPosteriorCondyle_z,medialEpicondyle_x,medialEpicondyle_y,medialEpicondyle_z,medialPosteriorCondyle_x,medialPosteriorCondyle_y,medialPosteriorCondyle_z,midfemurCenter_x,midfemurCenter_y,midfemurCenter_z
0,-138.02,22.78,984.23,-85.67,6.70,983.37,-116.63,12.84,496.29,-100.89,...,490.52,-31.03,15.25,496.03,-49.27,47.38,489.43,-98.24,-1.30,736.86
1,147.21,17.00,1486.54,100.45,-4.38,1473.25,170.56,-4.26,1072.43,152.07,...,1069.99,89.09,-20.00,1074.01,107.31,15.19,1070.64,140.35,-17.56,1270.99
2,155.50,-4.67,-78.89,98.97,-19.66,-77.10,117.15,-31.63,-530.33,93.37,...,-535.42,25.81,-44.83,-527.65,47.33,-6.16,-531.52,86.20,-54.74,-451.38
3,141.28,-115.56,-111.59,92.80,-126.56,-111.77,102.46,-98.17,-519.26,87.68,...,-523.79,20.86,-95.23,-520.61,41.68,-67.32,-524.07,93.89,-119.77,-320.51
4,143.21,-7.64,1301.63,89.04,-15.00,1289.36,165.37,-6.61,878.63,147.48,...,871.62,79.55,-16.27,869.35,95.72,16.73,865.51,130.59,-27.98,1078.46

In [13]:
# Transforming dataframe so that each patient is represented as 1 example to model

new_unknown_landmarks = []
for item in unknown_landmarks:
    new_unknown_landmarks.append(item + "_x")
    new_unknown_landmarks.append(item+"_y")
    new_unknown_landmarks.append(item+"_z")
    
new_df = []
for i in range(0, len(df_y), 3):
    row = [] 
    temp = df_y.iloc(0)
    for item in unknown_landmarks:
        row.append(temp[i][item])
        row.append(temp[i+1][item])
        row.append(temp[i+2][item])
    new_df.append(row)
    
new_df_y = pd.DataFrame(new_df)
new_df_y.columns = new_unknown_landmarks

In [14]:
new_df_y["PCLOrigin_x"].head()

0    -64.01
1    120.63
2     61.83
3     52.94
4    112.11
Name: PCLOrigin_x, dtype: float64

In [15]:
new_df_x.head()

,greaterTrochanter_x,greaterTrochanter_y,greaterTrochanter_z,hipCenter_x,hipCenter_y,hipCenter_z,lateralEpicondyle_x,lateralEpicondyle_y,lateralEpicondyle_z,lateralPosteriorCondyle_x,...,lateralPosteriorCondyle_z,medialEpicondyle_x,medialEpicondyle_y,medialEpicondyle_z,medialPosteriorCondyle_x,medialPosteriorCondyle_y,medialPosteriorCondyle_z,midfemurCenter_x,midfemurCenter_y,midfemurCenter_z
0,-138.02,22.78,984.23,-85.67,6.70,983.37,-116.63,12.84,496.29,-100.89,...,490.52,-31.03,15.25,496.03,-49.27,47.38,489.43,-98.24,-1.30,736.86
1,147.21,17.00,1486.54,100.45,-4.38,1473.25,170.56,-4.26,1072.43,152.07,...,1069.99,89.09,-20.00,1074.01,107.31,15.19,1070.64,140.35,-17.56,1270.99
2,155.50,-4.67,-78.89,98.97,-19.66,-77.10,117.15,-31.63,-530.33,93.37,...,-535.42,25.81,-44.83,-527.65,47.33,-6.16,-531.52,86.20,-54.74,-451.38
3,141.28,-115.56,-111.59,92.80,-126.56,-111.77,102.46,-98.17,-519.26,87.68,...,-523.79,20.86,-95.23,-520.61,41.68,-67.32,-524.07,93.89,-119.77,-320.51
4,143.21,-7.64,1301.63,89.04,-15.00,1289.36,165.37,-6.61,878.63,147.48,...,871.62,79.55,-16.27,869.35,95.72,16.73,865.51,130.59,-27.98,1078.46

In [16]:
def nans(df): return df[df.isnull().any(axis=1)]
nans(new_df_x)

Empty DataFrame
Columns: [greaterTrochanter_x, greaterTrochanter_y, greaterTrochanter_z, hipCenter_x, hipCenter_y, hipCenter_z, lateralEpicondyle_x, lateralEpicondyle_y, lateralEpicondyle_z, lateralPosteriorCondyle_x, lateralPosteriorCondyle_y, lateralPosteriorCondyle_z, medialEpicondyle_x, medialEpicondyle_y, medialEpicondyle_z, medialPosteriorCondyle_x, medialPosteriorCondyle_y, medialPosteriorCondyle_z, midfemurCenter_x, midfemurCenter_y, midfemurCenter_z]
Index: []

[0 rows x 21 columns]

# Model Training

In [17]:
from sklearn import linear_model

## PCLOrigin training

In [18]:
lm_x_po = linear_model.LinearRegression()
model_x = lm_x_po.fit(new_df_x,new_df_y["PCLOrigin_x"])
lm_y_po = linear_model.LinearRegression()
model_y = lm_y_po.fit(new_df_x,new_df_y["PCLOrigin_y"])
lm_z_po = linear_model.LinearRegression()
model_z = lm_z_po.fit(new_df_x,new_df_y["PCLOrigin_z"])

## lateralCondyle training

In [19]:
lm_x_lc = linear_model.LinearRegression()
model_x = lm_x_lc.fit(new_df_x,new_df_y["lateralCondyle_x"])
lm_y_lc = linear_model.LinearRegression()
model_y = lm_y_lc.fit(new_df_x,new_df_y["lateralCondyle_y"])
lm_z_lc = linear_model.LinearRegression()
model_z = lm_z_lc.fit(new_df_x,new_df_y["lateralCondyle_z"])

## medialCondyle training

In [20]:
lm_x_mc = linear_model.LinearRegression()
model_x = lm_x_mc.fit(new_df_x,new_df_y["medialCondyle_x"])
lm_y_mc = linear_model.LinearRegression()
model_y = lm_y_mc.fit(new_df_x,new_df_y["medialCondyle_y"])
lm_z_mc = linear_model.LinearRegression()
model_z = lm_z_mc.fit(new_df_x,new_df_y["medialCondyle_z"])

## medialSulcus training

In [21]:
lm_x_ms = linear_model.LinearRegression()
model_x = lm_x_ms.fit(new_df_x,new_df_y["medialSulcus_x"])
lm_y_ms = linear_model.LinearRegression()
model_y = lm_y_ms.fit(new_df_x,new_df_y["medialSulcus_y"])
lm_z_ms = linear_model.LinearRegression()
model_z = lm_z_ms.fit(new_df_x,new_df_y["medialSulcus_z"])

## whitesideReference training

In [22]:
lm_x_wr = linear_model.LinearRegression()
model_x = lm_x_wr.fit(new_df_x,new_df_y["whitesideReference_x"])
lm_y_wr = linear_model.LinearRegression()
model_y = lm_y_wr.fit(new_df_x,new_df_y["whitesideReference_y"])
lm_z_wr = linear_model.LinearRegression()
model_z = lm_z_wr.fit(new_df_x,new_df_y["whitesideReference_z"])

## femoralCenter training

In [23]:
lm_x_fc = linear_model.LinearRegression()
model_x = lm_x_fc.fit(new_df_x,new_df_y["femoralCenter_x"])
lm_y_fc = linear_model.LinearRegression()
model_y = lm_y_fc.fit(new_df_x,new_df_y["femoralCenter_y"])
lm_z_fc = linear_model.LinearRegression()
model_z = lm_z_fc.fit(new_df_x,new_df_y["femoralCenter_z"])

# Prediction testing

In [24]:
PATH = "/Users/apple/Desktop/Development/freelance/upwork/brad-miles/Landmarks-Detection/Dataset/csvs-test/"
files = glob.glob(PATH + '/*.csv', recursive=True)

In [25]:
# Loading test dataset
df = pd.DataFrame()
for file in files:
    df1 = pd.read_csv(file).transpose()
    temp = []
    for item in df1.iloc[0]:
        temp.append(item)
    df1.columns = temp
    df = df.append(df1[1:4])

In [26]:
# spliting test dataset
df_x = df[known_landmarks]
df_y = df[unknown_landmarks]

In [27]:
# transforming test dataset for prediction
new_known_landmarks = []
for item in df_x.columns:
    new_known_landmarks.append(item + "_x")
    new_known_landmarks.append(item+"_y")
    new_known_landmarks.append(item+"_z")
    
new_df = []
for i in range(0, len(df_x), 3):
    row = [] 
    temp = df_x.iloc(0)
    for item in known_landmarks:
        row.append(temp[i][item])
        row.append(temp[i+1][item])
        row.append(temp[i+2][item])
    new_df.append(row)
new_df_x = pd.DataFrame(new_df)
new_df_x.columns = new_known_landmarks

In [28]:
# transforming test dataset for prediction

new_unknown_landmarks = []
for item in unknown_landmarks:
    new_unknown_landmarks.append(item + "_x")
    new_unknown_landmarks.append(item+"_y")
    new_unknown_landmarks.append(item+"_z")
    
new_df = []
for i in range(0, len(df_y), 3):
    row = [] 
    temp = df_y.iloc(0)
    for item in unknown_landmarks:
        row.append(temp[i][item])
        row.append(temp[i+1][item])
        row.append(temp[i+2][item])
    new_df.append(row)
    
new_df_y = pd.DataFrame(new_df)
new_df_y.columns = new_unknown_landmarks

## PCL_orgin_test

In [29]:
#pedict PCL_origin 
predictions_x = lm_x_po.predict(new_df_x)
predictions_y = lm_y_po.predict(new_df_x)
predictions_z = lm_z_po.predict(new_df_x)
PCL_origin_predictions = []
for i, x in enumerate(predictions_z):
    PCL_origin_predictions.append([predictions_x[i], predictions_y[i], x])

In [30]:
PCL_origin_df = pd.DataFrame(PCL_origin_predictions)
PCL_origin_df.columns= ["PCLOrigin_x", "PCLOrigin_y", "PCLOrigin_z"]
print("\nPredicted Values!!!")
PCL_origin_df

Predicted Values!!!

   PCLOrigin_x  PCLOrigin_y  PCLOrigin_z
0   -76.025012   196.572946  -585.806961
1  -104.668108    29.301769  1289.404650
2    69.806745   -19.020267   495.172744
3   -79.772122    59.988493  -548.342390
4   -94.584642   -83.452609  1082.724580

In [31]:
print("\nActual Values!!!")
new_df_y[["PCLOrigin_x", "PCLOrigin_y", "PCLOrigin_z"]]

Actual Values!!!

   PCLOrigin_x  PCLOrigin_y  PCLOrigin_z
0       -75.14       197.36      -585.45
1      -101.97        30.50      1290.31
2        70.95       -17.85       497.53
3       -79.45        62.04      -547.40
4       -91.59       -83.50      1083.23

## lateralCondyle_test

In [32]:
#pedict lateralCondyle 
predictions_x = lm_x_lc.predict(new_df_x)
predictions_y = lm_y_lc.predict(new_df_x)
predictions_z = lm_z_lc.predict(new_df_x)
lateralCondyle_predictions = []
for i, x in enumerate(predictions_z):
    lateralCondyle_predictions.append([predictions_x[i], predictions_y[i], x])

In [33]:
lateralCondyle_df = pd.DataFrame(lateralCondyle_predictions)
lateralCondyle_df.columns= ["lateralCondyle_x", "lateralCondyle_y", "lateralCondyle_z"]
print("\nPredicted Values!!!")
lateralCondyle_df

Predicted Values!!!

   lateralCondyle_x  lateralCondyle_y  lateralCondyle_z
0       -109.543782        181.940733       -613.543408
1       -137.513216         12.805666       1261.731577
2        103.898493        -26.245734        465.927276
3       -113.934223         58.599080       -576.557642
4       -122.141904       -102.914872       1054.955593

In [34]:
print("\nActual Values!!!")
new_df_y[["lateralCondyle_x", "lateralCondyle_y", "lateralCondyle_z"]]

Actual Values!!!

   lateralCondyle_x  lateralCondyle_y  lateralCondyle_z
0           -106.40            182.61           -611.33
1           -134.20             13.70           1260.50
2            108.26            -23.42            467.10
3           -117.12             56.52           -578.37
4           -120.10           -103.12           1055.30

## medialCondyle_test

In [35]:
#predict medialCondyle
predictions_x = lm_x_mc.predict(new_df_x)
predictions_y = lm_y_mc.predict(new_df_x)
predictions_z = lm_z_mc.predict(new_df_x)
medialCondyle_predictions = []
for i, x in enumerate(predictions_z):
    medialCondyle_predictions.append([predictions_x[i], predictions_y[i], x])

In [36]:
medialCondyle_df = pd.DataFrame(medialCondyle_predictions)
medialCondyle_df.columns= ["medialCondyle_x", "medialCondyle_y", "medialCondyle_z"]
print("\nPredicted Values!!!")
medialCondyle_df

Predicted Values!!!

   medialCondyle_x  medialCondyle_y  medialCondyle_z
0       -60.949210       186.185416      -615.719265
1       -90.069266        21.134530      1258.792698
2        55.661922       -33.117265       464.159219
3       -69.483502        43.330153      -583.205502
4       -78.720390       -89.944957      1052.696893

In [37]:
print("\nActual Values!!!")
new_df_y[["medialCondyle_x", "medialCondyle_y", "medialCondyle_z"]]

Actual Values!!!

   medialCondyle_x  medialCondyle_y  medialCondyle_z
0           -57.85           185.83          -614.42
1           -86.45            20.24          1257.50
2            53.21           -34.21           464.92
3           -70.66            45.15          -584.51
4           -75.62           -89.93          1051.38

## medialSulcus_test

In [38]:
#predict medialSulcus

predictions_x = lm_x_ms.predict(new_df_x)
predictions_y = lm_y_ms.predict(new_df_x)
predictions_z = lm_z_ms.predict(new_df_x)
medialSulcus_predictions = []
for i, x in enumerate(predictions_z):
    medialSulcus_predictions.append([predictions_x[i], predictions_y[i], x])

In [39]:
medialSulcus_df = pd.DataFrame(medialSulcus_predictions)
medialSulcus_df.columns= ["medialSulcus_x", "medialSulcus_y", "medialSulcus_z"]
print("\nPredicted Values!!!")
medialSulcus_df

Predicted Values!!!

   medialSulcus_x  medialSulcus_y  medialSulcus_z
0      -41.700532      192.825881     -589.455984
1      -71.717326       28.067634     1282.748192
2       41.073496      -30.746099      489.787377
3      -56.865586       39.665395     -555.800408
4      -63.400595      -81.824345     1077.596729

In [40]:
print("\nActual Values!!!")
new_df_y[["medialSulcus_x", "medialSulcus_y", "medialSulcus_z"]]

Actual Values!!!

   medialSulcus_x  medialSulcus_y  medialSulcus_z
0          -44.80          192.01         -589.09
1          -74.17           27.67         1283.22
2           39.09          -31.13          490.15
3          -52.77           39.33         -554.73
4          -64.10          -83.18         1077.74

## whitesideReference_test

In [41]:
#predict whitesideReference
predictions_x = lm_x_wr.predict(new_df_x)
predictions_y = lm_y_wr.predict(new_df_x)
predictions_z = lm_z_wr.predict(new_df_x)
whitesideReference_predictions = []
for i, x in enumerate(predictions_z):
    whitesideReference_predictions.append([predictions_x[i], predictions_y[i], x])

In [42]:
whitesideReference_df = pd.DataFrame(whitesideReference_predictions)
whitesideReference_df.columns= ["whitesideReference_x", "whitesideReference_y", "whitesideReference_z"]
print("\nPredicted Values!!!")
whitesideReference_df

Predicted Values!!!

   whitesideReference_x  whitesideReference_y  whitesideReference_z
0            -86.140930            155.988577           -592.225344
1           -114.886341            -10.319509           1276.689863
2             84.186572            -57.738181            485.891394
3           -103.512243             21.471790           -558.832283
4            -96.889822           -123.080197           1071.156247

In [43]:
print("\nActual Values!!!")
new_df_y[["whitesideReference_x", "whitesideReference_y", "whitesideReference_z"]]

Actual Values!!!

   whitesideReference_x  whitesideReference_y  whitesideReference_z
0                -83.31                156.74               -592.80
1               -110.81                 -9.86               1280.81
2                 86.14                -51.62                484.81
3               -105.88                 23.68               -556.91
4                -92.70               -125.77               1072.24

## femoralCenter_test

In [44]:
#predict whitesideReference
predictions_x = lm_x_fc.predict(new_df_x)
predictions_y = lm_y_fc.predict(new_df_x)
predictions_z = lm_z_fc.predict(new_df_x)
femoralCenter_predictions = []
for i, x in enumerate(predictions_z):
    femoralCenter_predictions.append([predictions_x[i], predictions_y[i], x])

In [45]:
femoralCenter_df = pd.DataFrame(femoralCenter_predictions)
femoralCenter_df.columns= ["femoralCenter_x", "femoralCenter_y", "femoralCenter_z"]
print("\nPredicted Values!!!")
femoralCenter_df

Predicted Values!!!

   femoralCenter_x  femoralCenter_y  femoralCenter_z
0       -86.269406       175.000319      -604.641149
1      -115.988112         8.869025      1262.843809
2        81.863955       -37.505339       471.133814
3       -96.274933        41.965886      -573.025762
4       -99.949547      -104.565515      1059.483676

In [46]:
print("\nActual Values!!!")
new_df_y[["femoralCenter_x", "femoralCenter_y", "femoralCenter_z"]]

Actual Values!!!

   femoralCenter_x  femoralCenter_y  femoralCenter_z
0           -85.11           178.88          -606.50
1          -112.31             9.37          1266.51
2            85.01           -38.92           474.68
3           -98.37            45.57          -573.35
4           -97.46          -106.34          1061.26